// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by $AppName$ $AppVersion$
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container$GallerySuffix$").wowSlider({effect:"$ImageEffect$",prev:"$prevCaption$",next:"$nextCaption$",duration:$SlideshowDuration$*100,delay:$SlideshowDelay$*100,width:$ImageWidth$,height:$ImageHeight$,autoPlay:$AutoPlay$,autoPlayVideo:$AutoPlayVideo$,playPause:$PlayPause$,stopOnHover:$StopOnHover$,loop:$OneLoop$,bullets:$ShowBullets$,caption:$Captions$,captionEffect:"$CaptionsEffect$",controls:$Controls$,controlsThumb:$ArrowThumbs$,responsive:$SizeStyle$,fullScreen:$FullScreen$,gestures:$SwipeSupport$,onBeforeStep:$OnBeforeStep$,images:$JSONList$});