// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by $AppName$ $AppVersion$
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_squares(i,h,b){var e=jQuery;var g=e(this);var f=b.find("ul").get(0);f.id="wowslider_tmp"+Math.round(Math.random()*99999);var c=0;e(f).coinslider({hoverPause:false,startSlide:i.startSlide,navigation:0,delay:-1,effect:i.type,width:i.width,height:i.height,sDelay:i.duration/(7*5)});var d=e("#coin-slider-"+f.id).addClass("ws_effect ws_squares").css({position:"absolute",display:"none",left:0,top:0,"z-index":8,transform:"translate3d(0,0,0)"});var a=i.startSlide;e(f).bind("cs:animFinished",function(){g.trigger("effectEnd");if(c<2){c=0;d.hide()}});this.go=function(j){c++;d.show();a=j;e.transition(f,j);d.css("background","none");if(i.fadeOut){e(f).fadeOut(i.duration)}}};