//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebViecLammoi.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebViecLammoi.i18n.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation Name.
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative formalities.
        /// </summary>
        public static string Administrativeformalities {
            get {
                return ResourceManager.GetString("Administrativeformalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of Employer.
        /// </summary>
        public static string AmountPeople {
            get {
                return ResourceManager.GetString("AmountPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Date.
        /// </summary>
        public static string AppDate {
            get {
                return ResourceManager.GetString("AppDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit.
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        public static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANDIDATE INFORMATION.
        /// </summary>
        public static string CanInfo {
            get {
                return ResourceManager.GetString("CanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string Catalog {
            get {
                return ResourceManager.GetString("Catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENTRE OF.
        /// </summary>
        public static string Centre {
            get {
                return ResourceManager.GetString("Centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Account Information.
        /// </summary>
        public static string ChangeAccInfo {
            get {
                return ResourceManager.GetString("ChangeAccInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Background Color.
        /// </summary>
        public static string Changecolor {
            get {
                return ResourceManager.GetString("Changecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Location.
        /// </summary>
        public static string Changelocation {
            get {
                return ResourceManager.GetString("Changelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check The Status Of Unemployment Insurance Record.
        /// </summary>
        public static string CheckBHTNRecord {
            get {
                return ResourceManager.GetString("CheckBHTNRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip.
        /// </summary>
        public static string Clip {
            get {
                return ResourceManager.GetString("Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID Number Or Social Security Number To Check.
        /// </summary>
        public static string CMNDorBHXH {
            get {
                return ResourceManager.GetString("CMNDorBHXH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Id.
        /// </summary>
        public static string Codeofcandidate {
            get {
                return ResourceManager.GetString("Codeofcandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Id.
        /// </summary>
        public static string Codeofcompany {
            get {
                return ResourceManager.GetString("Codeofcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPANY INFORMATION.
        /// </summary>
        public static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level.
        /// </summary>
        public static string Computerlevel {
            get {
                return ResourceManager.GetString("Computerlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Centre For Detail Information.
        /// </summary>
        public static string ContactforInfo {
            get {
                return ResourceManager.GetString("ContactforInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Place.
        /// </summary>
        public static string CurrentPlace {
            get {
                return ResourceManager.GetString("CurrentPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Issued.
        /// </summary>
        public static string DateIssued {
            get {
                return ResourceManager.GetString("DateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE NOTICE.
        /// </summary>
        public static string DateNotice {
            get {
                return ResourceManager.GetString("DateNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deputy.
        /// </summary>
        public static string Deputy {
            get {
                return ResourceManager.GetString("Deputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe More.
        /// </summary>
        public static string DescribeMore {
            get {
                return ResourceManager.GetString("DescribeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desire Career.
        /// </summary>
        public static string DesireCareer {
            get {
                return ResourceManager.GetString("DesireCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty.
        /// </summary>
        public static string Duty {
            get {
                return ResourceManager.GetString("Duty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/Delete.
        /// </summary>
        public static string Edit_Del {
            get {
                return ResourceManager.GetString("Edit_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational level.
        /// </summary>
        public static string Educationallevel {
            get {
                return ResourceManager.GetString("Educationallevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Day.
        /// </summary>
        public static string EndDay {
            get {
                return ResourceManager.GetString("EndDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Established Year.
        /// </summary>
        public static string EstablishedYear {
            get {
                return ResourceManager.GetString("EstablishedYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Of This Candidate.
        /// </summary>
        public static string Fileofthiscandidate {
            get {
                return ResourceManager.GetString("Fileofthiscandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill All The Information:.
        /// </summary>
        public static string FillInfo {
            get {
                return ResourceManager.GetString("FillInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the Right Candidate for your Business.
        /// </summary>
        public static string FindRiteCan {
            get {
                return ResourceManager.GetString("FindRiteCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find The Right Job For You.
        /// </summary>
        public static string FindRiteJob {
            get {
                return ResourceManager.GetString("FindRiteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Language Level.
        /// </summary>
        public static string ForeignLanguage {
            get {
                return ResourceManager.GetString("ForeignLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget.
        /// </summary>
        public static string Forget {
            get {
                return ResourceManager.GetString("Forget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Your Username - You will receive your password via your registered email.
        /// </summary>
        public static string ForgetPassTitle {
            get {
                return ResourceManager.GetString("ForgetPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headquarter.
        /// </summary>
        public static string HeadQuarter {
            get {
                return ResourceManager.GetString("HeadQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot news.
        /// </summary>
        public static string Hotnews {
            get {
                return ResourceManager.GetString("Hotnews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        public static string IDNum {
            get {
                return ResourceManager.GetString("IDNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Img {
            get {
                return ResourceManager.GetString("Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information On Unemployment Insurance policies.
        /// </summary>
        public static string InfoOfBHTN {
            get {
                return ResourceManager.GetString("InfoOfBHTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructures.
        /// </summary>
        public static string Infrastructures {
            get {
                return ResourceManager.GetString("Infrastructures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Requirements.
        /// </summary>
        public static string JobRequirements {
            get {
                return ResourceManager.GetString("JobRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest Candidates.
        /// </summary>
        public static string LastestCandidate {
            get {
                return ResourceManager.GetString("LastestCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Leave Your Message..
        /// </summary>
        public static string LeaveMess {
            get {
                return ResourceManager.GetString("LeaveMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Documents.
        /// </summary>
        public static string Legal_documents {
            get {
                return ResourceManager.GetString("Legal_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Management.
        /// </summary>
        public static string ManageCan {
            get {
                return ResourceManager.GetString("ManageCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Management.
        /// </summary>
        public static string ManageCre {
            get {
                return ResourceManager.GetString("ManageCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Number.
        /// </summary>
        public static string MonthNum {
            get {
                return ResourceManager.GetString("MonthNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LABOUR SERVICES BINH DUONG PROVINCE.
        /// </summary>
        public static string NameofCentre {
            get {
                return ResourceManager.GetString("NameofCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Document.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Of Unemployment Insurance.
        /// </summary>
        public static string NewsOfBHTN {
            get {
                return ResourceManager.GetString("NewsOfBHTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Visit.
        /// </summary>
        public static string NumOfVisit {
            get {
                return ResourceManager.GetString("NumOfVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online job fair.
        /// </summary>
        public static string Onlinejobfair {
            get {
                return ResourceManager.GetString("Onlinejobfair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organigrama.
        /// </summary>
        public static string Organigrama {
            get {
                return ResourceManager.GetString("Organigrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Skills.
        /// </summary>
        public static string OtherSkills {
            get {
                return ResourceManager.GetString("OtherSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONAL INFORMATION.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Of Receipt.
        /// </summary>
        public static string PlaceofReceipt {
            get {
                return ResourceManager.GetString("PlaceofReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE INFORMATION.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitments.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECRUITMENT INFORMATION.
        /// </summary>
        public static string RecruitmentInfo {
            get {
                return ResourceManager.GetString("RecruitmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment of this company.
        /// </summary>
        public static string Recruitmentofthiscompany {
            get {
                return ResourceManager.GetString("Recruitmentofthiscompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment Position.
        /// </summary>
        public static string RecruitmentPosition {
            get {
                return ResourceManager.GetString("RecruitmentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Form For Unemployment Insurance.
        /// </summary>
        public static string RegBHTN {
            get {
                return ResourceManager.GetString("RegBHTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement More.
        /// </summary>
        public static string RequirementMore {
            get {
                return ResourceManager.GetString("RequirementMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result :.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Send For Approval.
        /// </summary>
        public static string SaveandSubmit {
            get {
                return ResourceManager.GetString("SaveandSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveCan {
            get {
                return ResourceManager.GetString("SaveCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Candidates.
        /// </summary>
        public static string SavedCan {
            get {
                return ResourceManager.GetString("SavedCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Recruitments.
        /// </summary>
        public static string SavedCre {
            get {
                return ResourceManager.GetString("SavedCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Information.
        /// </summary>
        public static string SaveInfo {
            get {
                return ResourceManager.GetString("SaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveJob {
            get {
                return ResourceManager.GetString("SaveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchBy.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password.
        /// </summary>
        public static string SendPass {
            get {
                return ResourceManager.GetString("SendPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Salary.
        /// </summary>
        public static string StartingSalary {
            get {
                return ResourceManager.GetString("StartingSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical.
        /// </summary>
        public static string Statistical {
            get {
                return ResourceManager.GetString("Statistical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS OF RECORDS.
        /// </summary>
        public static string StatusofRecords {
            get {
                return ResourceManager.GetString("StatusofRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suitable Candidates.
        /// </summary>
        public static string Suitable_Can {
            get {
                return ResourceManager.GetString("Suitable_Can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suitable Recruitments.
        /// </summary>
        public static string Suitable_Cre {
            get {
                return ResourceManager.GetString("Suitable_Cre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical level.
        /// </summary>
        public static string Technicallevel {
            get {
                return ResourceManager.GetString("Technicallevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Day Can Start Work.
        /// </summary>
        public static string Thedaycanstartwork {
            get {
                return ResourceManager.GetString("Thedaycanstartwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Company.
        /// </summary>
        public static string TypeOfCompany {
            get {
                return ResourceManager.GetString("TypeOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapprove.
        /// </summary>
        public static string Unapprove {
            get {
                return ResourceManager.GetString("Unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployment Insurance.
        /// </summary>
        public static string Unemp_insurance {
            get {
                return ResourceManager.GetString("Unemp_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Delete.
        /// </summary>
        public static string View_Del {
            get {
                return ResourceManager.GetString("View_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for approved.
        /// </summary>
        public static string WaitApprove {
            get {
                return ResourceManager.GetString("WaitApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ward.
        /// </summary>
        public static string Ward {
            get {
                return ResourceManager.GetString("Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where To Apply.
        /// </summary>
        public static string WheretoApply {
            get {
                return ResourceManager.GetString("WheretoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where To Work.
        /// </summary>
        public static string WheretoWork {
            get {
                return ResourceManager.GetString("WheretoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string Wish {
            get {
                return ResourceManager.GetString("Wish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time.
        /// </summary>
        public static string WorkingTime {
            get {
                return ResourceManager.GetString("WorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work on request.
        /// </summary>
        public static string Workonrequest {
            get {
                return ResourceManager.GetString("Workonrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Documents.
        /// </summary>
        public static string YourFile {
            get {
                return ResourceManager.GetString("YourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Recruitment Document.
        /// </summary>
        public static string YourjobFile {
            get {
                return ResourceManager.GetString("YourjobFile", resourceCulture);
            }
        }
    }
}
